<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Dependency-free QR Code Model 2 encoder for .NET.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/SpecQR/SpecQR-CSharp</RepositoryUrl>
    <Version>0.1.0</Version>
  </PropertyGroup>
</Project>
